services:
  agent:
    build: 
      context: .
      args:
        user_uid: "$USER_UID"
        user_gid: "$USER_GID"
    container_name: forex-signal-agent
    restart: unless-stopped
    
    env_file:
      - .env
    environment:
      - TZ=Europe/Moscow
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - SQLITE_PATH=/app/data/cache.db
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./data:/app/data
      - ./logs:/app/logs
    command: ["forex-signal-agent", "--config", "/app/config.yaml"]
